window.ALFA_FLOW_DATA = {
  layers: [
    { id: 'L0', title: '任务级', desc: '20 箱任务整体生命周期', color: 'violet' },
    { id: 'L1', title: '循环级', desc: '一轮识别到一次抓取任务汇总', color: 'blue' },
    { id: 'L2', title: '动作阶段级', desc: '抓取、搬运、放置的最小状态', color: 'green' },
    { id: 'L3', title: '场景 / 安全 / 结果级', desc: 'MoveIt 场景、异常、安全、slot 汇总', color: 'amber' }
  ],
  states: [
    { id:'INIT', stage:'arm_initialized', layer:'L0', title:'系统初始化', type:'normal', desc:'电机、气路、通信、安全状态自检，机械臂进入初始位。', reads:['mission_config','safety_state','joint_state'], writes:['arm_home_state','stage_result'], success:'通信、安全、初始姿态全部可用。', failures:['init_failed','safety_not_ready','communication_abnormal'], recovery:['retry_init','manual_intervention','emergency_stop'], next:['WAIT_START'], slot:false, scene:false, note:'这是任务开始前的系统可信度门槛。' },
    { id:'WAIT_START', stage:'mission_started', layer:'L0', title:'等待启动', type:'decision', desc:'等待人工启动一轮 V1 连续卸箱任务。', reads:['mission_config','operator_command'], writes:['mission_state','stage_result'], success:'收到启动指令并创建 mission_id。', failures:['start_rejected'], recovery:['wait_operator'], next:['MOVE_TO_WORKPOSE'], slot:false, scene:false, note:'人工只启动整轮任务，不逐箱遥操作。' },
    { id:'MOVE_TO_WORKPOSE', stage:'chassis_arrived', layer:'L1', title:'底盘到作业位', type:'normal', desc:'底盘到达可识别、可抓取、可放置的作业位置。', reads:['mission_state','chassis_state'], writes:['chassis_state','stage_result'], success:'到位且定位可信度达标。', failures:['chassis_not_arrived','pose_abnormal'], recovery:['reposition_chassis','manual_intervention'], next:['WAIT_PERCEPTION'], slot:false, scene:false, note:'底盘位置会影响后续可达性和视觉坐标可信度。' },
    { id:'WAIT_PERCEPTION', stage:'perception_received', layer:'L1', title:'等待视觉结果', type:'normal', desc:'触发或等待视觉识别，形成本轮 perception_frame。', reads:['chassis_state','arm_home_state'], writes:['perception_frame','stage_result'], success:'拿到有效 perception_frame。', failures:['no_target','low_confidence','transform_failed'], recovery:['re_perception','reposition_chassis'], next:['VALIDATE_TARGETS'], slot:false, scene:false, note:'感知批次是后续目标身份追踪的起点。' },
    { id:'VALIDATE_TARGETS', stage:'targets_validated', layer:'L1', title:'识别结果校验', type:'decision', desc:'检查目标数量、位姿、尺寸、坐标转换和可吸附面。', reads:['perception_frame','grasp_target'], writes:['validated_targets','stage_result'], success:'至少存在可进入目标选择的候选目标。', failures:['pose_abnormal','target_geometry_missing','no_graspable_face'], recovery:['re_perception','reposition_chassis'], next:['SELECT_TARGETS'], slot:false, scene:false, note:'目标几何字段必须存在，当前可用固定尺寸覆盖检测值。' },
    { id:'SELECT_TARGETS', stage:'targets_selected', layer:'L1', title:'选择左右目标', type:'decision', desc:'按规则从上到下、从左到右，选择本轮左右手最多两个目标。', reads:['validated_targets','target_history'], writes:['target_selection','stage_result'], success:'生成 target_selection。', failures:['no_reachable_target','selection_empty'], recovery:['re_perception','reposition_chassis'], next:['CREATE_PICK_TASK'], slot:false, scene:false, note:'这是决策程序和运控执行之间的分界。' },
    { id:'CREATE_PICK_TASK', stage:'pick_task_created', layer:'L1', title:'生成抓取任务', type:'normal', desc:'把视觉目标变成一次双臂执行任务，绑定 left/right slot。', reads:['target_selection','grasp_target'], writes:['pick_task','stage_result'], success:'pick_task_id 与左右槽位生成完成。', failures:['task_build_failed'], recovery:['re_perception'], next:['UPDATE_WORLD_SCENE'], slot:false, scene:false, note:'从这里开始进入一次具体双臂抓取任务。' },
    { id:'UPDATE_WORLD_SCENE', stage:'scene_world_updated', layer:'L3', title:'更新世界箱体', type:'scene', desc:'把本轮目标作为 MoveIt world object 加入规划场景。', reads:['pick_task','target_geometry','grasp_target.pose'], writes:['moveit_scene_update','stage_result'], success:'box_world_<target_id> 添加成功。', failures:['scene_update_failed'], recovery:['re_perception','manual_intervention'], next:['PLAN_PREGRASP'], slot:true, scene:true, note:'MoveIt 场景更新是硬门槛，不是可选可视化。' },
    { id:'PLAN_PREGRASP', stage:'pre_grasp_planned', layer:'L2', title:'预抓取规划', type:'motion', desc:'为左右手生成到预抓取位姿的规划。', reads:['pick_task','moveit_scene_update','joint_state'], writes:['trajectory_result','stage_result'], success:'轨迹可行且碰撞检查通过。', failures:['ik_failed','planning_failed','collision_detected'], recovery:['retry_same_target','mark_target_failed','re_perception'], next:['MOVE_PREGRASP'], slot:true, scene:false, note:'规划结果应记录失败原因，不能只给 false。' },
    { id:'MOVE_PREGRASP', stage:'pre_grasp_reached', layer:'L2', title:'到达预抓取位姿', type:'motion', desc:'执行预抓取轨迹，左右末端到达箱子前方安全位置。', reads:['trajectory_result','controller_state'], writes:['stage_result','joint_state'], success:'控制器执行完成且末端误差达标。', failures:['execution_failed','cartesian_error_too_large'], recovery:['retry_same_target','re_perception'], next:['ENABLE_VACUUM'], slot:true, scene:false, note:'该状态改变机器人姿态，因此是独立最小状态。' },
    { id:'ENABLE_VACUUM', stage:'vacuum_enabled', layer:'L2', title:'打开气泵', type:'actuator', desc:'对参与抓取的 slot 打开真空。', reads:['pick_task','vacuum_state'], writes:['vacuum_command','stage_result'], success:'气泵命令下发成功。', failures:['vacuum_command_failed'], recovery:['retry_same_target','manual_intervention'], next:['APPROACH_CONTACT'], slot:true, scene:false, note:'开泵和真空确认不能混成同一个状态。' },
    { id:'APPROACH_CONTACT', stage:'approach_contacted', layer:'L2', title:'贴近并接触', type:'motion', desc:'沿靠近方向做笛卡尔直线或约束运动，直到吸盘接触目标面。', reads:['pick_task','approach_direction','force_state'], writes:['stage_result','contact_state'], success:'接触力或位姿达到接触条件。', failures:['no_contact','force_abnormal','execution_failed'], recovery:['retry_same_target','re_perception','emergency_stop'], next:['CHECK_VACUUM'], slot:true, scene:false, note:'贴近失败和真空失败是不同问题。' },
    { id:'CHECK_VACUUM', stage:'vacuum_confirmed', layer:'L2', title:'真空确认', type:'actuator', desc:'检查真空阈值和稳定持续时间，确认是否吸住。', reads:['vacuum_state','pick_task'], writes:['stage_result'], success:'真空值达到阈值并稳定。', failures:['vacuum_abnormal','vacuum_timeout'], recovery:['retry_same_target','re_perception'], next:['ATTACH_BOX_MODEL'], slot:true, scene:false, note:'只有成功后才能 attach 箱体模型。' },
    { id:'ATTACH_BOX_MODEL', stage:'scene_attached_updated', layer:'L3', title:'附着箱体模型', type:'scene', desc:'把已吸住的箱体从 world object 变成 attached object。', reads:['pick_task','moveit_scene_update'], writes:['moveit_scene_update','stage_result'], success:'box_attached_<slot>_<target_id> 绑定成功。', failures:['scene_update_failed'], recovery:['re_perception','manual_intervention'], next:['PLAN_EXTRACT'], slot:true, scene:true, note:'现实吸住后，规划世界必须同步。' },
    { id:'PLAN_EXTRACT', stage:'extract_planned', layer:'L2', title:'规划拉出路径', type:'motion', desc:'在带箱状态下规划从堆垛中拉出或抬离的路径。', reads:['attached_object','joint_state','moveit_scene_update'], writes:['trajectory_result','stage_result'], success:'带箱规划成功且碰撞检查通过。', failures:['planning_failed','collision_detected'], recovery:['retry_same_target','re_perception'], next:['EXTRACT_BOX'], slot:true, scene:false, note:'这里必须使用 attached object 后的场景。' },
    { id:'EXTRACT_BOX', stage:'extract_executed', layer:'L2', title:'拉出箱体', type:'motion', desc:'执行拉出或抬离动作，并持续监控真空和末端力。', reads:['trajectory_result','vacuum_state','force_state'], writes:['stage_result','object_state'], success:'箱体离开堆垛且吸附稳定。', failures:['partial_pullout','dropped_after_pullout','force_abnormal','vacuum_abnormal'], recovery:['re_perception','emergency_stop','manual_intervention'], next:['PLAN_CARRY'], slot:true, scene:false, note:'一旦箱子真实位置变化，通常需要重新识别。' },
    { id:'PLAN_CARRY', stage:'transfer_planned', layer:'L2', title:'规划搬运路径', type:'motion', desc:'规划带箱从当前位置到卸货平台入口区域的轨迹。', reads:['attached_object','unload_platform_pose','moveit_scene_update'], writes:['trajectory_result','stage_result'], success:'搬运轨迹可行。', failures:['planning_failed','collision_detected'], recovery:['retry_same_target','re_perception'], next:['CARRY_BOX'], slot:true, scene:false, note:'带箱规划必须考虑箱体尺寸和碰撞体。' },
    { id:'CARRY_BOX', stage:'transfer_executed', layer:'L2', title:'搬运到平台', type:'motion', desc:'带箱执行搬运轨迹，监控真空、力和控制器状态。', reads:['trajectory_result','vacuum_state','force_state'], writes:['stage_result','object_state'], success:'到达卸货平台区域且箱体仍稳定。', failures:['vacuum_abnormal','force_abnormal','execution_failed','dropped_during_transfer'], recovery:['emergency_stop','re_perception','manual_intervention'], next:['REACH_PLACE_POSE'], slot:true, scene:false, note:'带载搬运是高风险阶段，异常优先安全。' },
    { id:'REACH_PLACE_POSE', stage:'place_reached', layer:'L2', title:'到达放置位', type:'motion', desc:'末端或箱体到达卸货平台入口的放置位姿。', reads:['unload_platform_pose','joint_state'], writes:['stage_result'], success:'位姿误差达标。', failures:['execution_failed','cartesian_error_too_large'], recovery:['retry_same_target','manual_intervention'], next:['CONFIRM_PLACE_CONTACT'], slot:true, scene:false, note:'到位不等于放好，必须再确认接触。' },
    { id:'CONFIRM_PLACE_CONTACT', stage:'place_contact_confirmed', layer:'L2', title:'确认平台接触', type:'actuator', desc:'通过力控确认箱子和平台较好接触。', reads:['force_state','unload_platform_pose'], writes:['stage_result','contact_state'], success:'法向力或接触条件达标。', failures:['no_contact','force_abnormal'], recovery:['retry_same_target','manual_intervention'], next:['DISABLE_VACUUM'], slot:true, scene:false, note:'接触异常时不应该直接关闭真空。' },
    { id:'DISABLE_VACUUM', stage:'vacuum_disabled', layer:'L2', title:'关闭气泵', type:'actuator', desc:'关闭或破真空，使箱子脱离吸盘。', reads:['vacuum_state','contact_state'], writes:['vacuum_command','stage_result'], success:'真空释放完成。', failures:['vacuum_release_failed'], recovery:['manual_intervention'], next:['UPDATE_PLACED_SCENE'], slot:true, scene:false, note:'释放后必须更新场景，否则下轮规划不可信。' },
    { id:'UPDATE_PLACED_SCENE', stage:'scene_placed_updated', layer:'L3', title:'更新放置场景', type:'scene', desc:'将 attached object 变成 placed 或 removed object，保证 MoveIt 世界一致。', reads:['attached_object','unload_platform_pose'], writes:['moveit_scene_update','stage_result'], success:'detach/place/remove 成功。', failures:['scene_update_failed'], recovery:['manual_intervention','re_perception'], next:['RETREAT_SAFE'], slot:true, scene:true, note:'scene update 失败时不能继续正常下一轮。' },
    { id:'RETREAT_SAFE', stage:'retreat_safe_reached', layer:'L2', title:'末端安全退出', type:'motion', desc:'释放后吸盘退出到安全位置。', reads:['joint_state','moveit_scene_update'], writes:['stage_result','joint_state'], success:'末端退出安全区域。', failures:['execution_failed'], recovery:['manual_intervention'], next:['AGGREGATE_SLOT_RESULTS'], slot:true, scene:false, note:'安全退出后才能汇总结果。' },
    { id:'AGGREGATE_SLOT_RESULTS', stage:'slot_results_aggregated', layer:'L3', title:'汇总左右结果', type:'result', desc:'把左右手阶段结果汇总为 slot_result 和 pick_task_result。', reads:['stage_result','slot_result'], writes:['slot_result','pick_task_result'], success:'生成 success / partial_success / failed / aborted。', failures:['aggregation_failed'], recovery:['manual_intervention'], next:['DECIDE_NEXT'], slot:false, scene:false, note:'这里体现单手成功、单手失败。' },
    { id:'DECIDE_NEXT', stage:'next_step_decided', layer:'L1', title:'决定下一步', type:'decision', desc:'根据任务汇总结果决定下一轮识别、底盘调整、完成或人工恢复。', reads:['pick_task_result','mission_state'], writes:['mission_state','stage_result'], success:'下一状态确定。', failures:['decision_failed'], recovery:['manual_intervention'], next:['WAIT_PERCEPTION','MOVE_TO_WORKPOSE','TASK_COMPLETE','WAIT_MANUAL_RECOVERY'], slot:false, scene:false, note:'闭环从这里回到下一轮识别。' },
    { id:'TASK_COMPLETE', stage:'mission_completed', layer:'L0', title:'任务完成', type:'result', desc:'连续任务达成验收条件，保存报告和证据。', reads:['mission_state','test_report'], writes:['test_report','mission_state'], success:'达到目标箱数和验收口径。', failures:[], recovery:[], next:[], slot:false, scene:false, note:'最终目标是连续 20 箱自主卸箱闭环。' },
    { id:'WAIT_MANUAL_RECOVERY', stage:'manual_recovery_waiting', layer:'L3', title:'等待人工恢复', type:'safety', desc:'自动恢复失败或场景不可信时，等待人工处理。', reads:['safety_event','recovery_action'], writes:['stage_result','mission_state'], success:'人工确认恢复。', failures:[], recovery:[], next:['WAIT_PERCEPTION','MOVE_TO_WORKPOSE'], slot:false, scene:false, note:'人工恢复后通常重新识别或重新到位。' },
    { id:'E_STOP', stage:'emergency_stopped', layer:'L3', title:'急停', type:'safety', desc:'严重安全风险或急停触发，停止执行。', reads:['safety_event'], writes:['stage_result','mission_state'], success:'系统进入安全停机。', failures:[], recovery:['manual_intervention'], next:['WAIT_MANUAL_RECOVERY'], slot:false, scene:false, note:'急停后不能自动继续。' }
  ],
  edges: [
    ['INIT','WAIT_START'], ['WAIT_START','MOVE_TO_WORKPOSE'], ['MOVE_TO_WORKPOSE','WAIT_PERCEPTION'], ['WAIT_PERCEPTION','VALIDATE_TARGETS'], ['VALIDATE_TARGETS','SELECT_TARGETS'], ['SELECT_TARGETS','CREATE_PICK_TASK'], ['CREATE_PICK_TASK','UPDATE_WORLD_SCENE'], ['UPDATE_WORLD_SCENE','PLAN_PREGRASP'], ['PLAN_PREGRASP','MOVE_PREGRASP'], ['MOVE_PREGRASP','ENABLE_VACUUM'], ['ENABLE_VACUUM','APPROACH_CONTACT'], ['APPROACH_CONTACT','CHECK_VACUUM'], ['CHECK_VACUUM','ATTACH_BOX_MODEL'], ['ATTACH_BOX_MODEL','PLAN_EXTRACT'], ['PLAN_EXTRACT','EXTRACT_BOX'], ['EXTRACT_BOX','PLAN_CARRY'], ['PLAN_CARRY','CARRY_BOX'], ['CARRY_BOX','REACH_PLACE_POSE'], ['REACH_PLACE_POSE','CONFIRM_PLACE_CONTACT'], ['CONFIRM_PLACE_CONTACT','DISABLE_VACUUM'], ['DISABLE_VACUUM','UPDATE_PLACED_SCENE'], ['UPDATE_PLACED_SCENE','RETREAT_SAFE'], ['RETREAT_SAFE','AGGREGATE_SLOT_RESULTS'], ['AGGREGATE_SLOT_RESULTS','DECIDE_NEXT'], ['DECIDE_NEXT','WAIT_PERCEPTION','下一轮'], ['DECIDE_NEXT','MOVE_TO_WORKPOSE','底盘调整'], ['DECIDE_NEXT','TASK_COMPLETE','完成'], ['DECIDE_NEXT','WAIT_MANUAL_RECOVERY','人工恢复'], ['CARRY_BOX','E_STOP','高风险异常']
  ],
  dataObjects: [
    { id:'mission_state', title:'任务状态', producer:'WAIT_START / DECIDE_NEXT', consumers:['MOVE_TO_WORKPOSE','TASK_COMPLETE'], fields:['mission_id','target_box_count','completed_box_count','mission_status'], desc:'20 箱任务整体状态。' },
    { id:'chassis_state', title:'底盘状态', producer:'MOVE_TO_WORKPOSE', consumers:['WAIT_PERCEPTION','MOVE_TO_WORKPOSE'], fields:['pose','arrived','confidence'], desc:'底盘是否到作业位，以及定位可信度。' },
    { id:'arm_home_state', title:'机械臂初始位', producer:'INIT', consumers:['WAIT_PERCEPTION'], fields:['home_name','joint_state','ready'], desc:'确认机械臂处于可开始视觉和抓取的初始状态。' },
    { id:'perception_frame', title:'感知批次', producer:'WAIT_PERCEPTION', consumers:['VALIDATE_TARGETS','SELECT_TARGETS'], fields:['perception_frame_id','status','targets[]','frame_id'], desc:'一次视觉识别看到的所有候选目标。' },
    { id:'grasp_target', title:'抓取目标数据', producer:'VALIDATE_TARGETS', consumers:['SELECT_TARGETS','CREATE_PICK_TASK','UPDATE_WORLD_SCENE'], fields:['target_id','pose','target_geometry','confidence','grasp_face'], desc:'某个箱子的标准抓取数据，不是六个裸数字。' },
    { id:'target_selection', title:'目标选择', producer:'SELECT_TARGETS', consumers:['CREATE_PICK_TASK'], fields:['selection_id','policy','left.target_id','right.target_id'], desc:'本轮左右手分别准备抓哪个目标。' },
    { id:'pick_task', title:'抓取任务', producer:'CREATE_PICK_TASK', consumers:['UPDATE_WORLD_SCENE','PLAN_PREGRASP','CHECK_VACUUM'], fields:['pick_task_id','slots.left','slots.right','tip_link','object_id'], desc:'一次真正执行的双臂抓取任务。' },
    { id:'trajectory_result', title:'轨迹结果', producer:'PLAN_*', consumers:['MOVE_PREGRASP','EXTRACT_BOX','CARRY_BOX'], fields:['trajectory_id','planning_group','points','planning_time_ms','collision_result'], desc:'规划器输出的轨迹和规划诊断。' },
    { id:'vacuum_state', title:'真空状态', producer:'硬件/气泵', consumers:['ENABLE_VACUUM','CHECK_VACUUM','CARRY_BOX'], fields:['vacuum_kpa','threshold_kpa','stable_duration_ms'], desc:'判断是否吸住和搬运中是否泄漏。' },
    { id:'force_state', title:'末端力状态', producer:'末端传感器/力控', consumers:['APPROACH_CONTACT','CONFIRM_PLACE_CONTACT','CARRY_BOX'], fields:['force_n','normal_force_n','contact_threshold_n'], desc:'用于接触确认、异常力检测和放置确认。' },
    { id:'stage_result', title:'阶段执行结果', producer:'每个状态', consumers:['AGGREGATE_SLOT_RESULTS','日志/复盘'], fields:['stage','status','slot','metrics','recovery_action'], desc:'某个状态发生了什么，不把失败原因和恢复动作混在一起。' },
    { id:'slot_result', title:'槽位结果', producer:'AGGREGATE_SLOT_RESULTS', consumers:['pick_task_result','DECIDE_NEXT'], fields:['slot','target_id','final_status','final_object_state'], desc:'left/right 独立成功或失败。' },
    { id:'pick_task_result', title:'任务汇总结果', producer:'AGGREGATE_SLOT_RESULTS', consumers:['DECIDE_NEXT','测试报告'], fields:['task_status','slots.left','slots.right','next_decision'], desc:'本次双臂抓取任务总结果，允许 partial_success。' },
    { id:'moveit_scene_update', title:'MoveIt 场景更新', producer:'UPDATE_WORLD_SCENE / ATTACH / PLACE / DROP', consumers:['PLAN_PREGRASP','PLAN_EXTRACT','PLAN_CARRY'], fields:['operation','object_id','target_id','from_state','to_state','status'], desc:'保持规划世界和现实箱子状态一致。' }
  ],
  recoveryRules: [
    { source:'WAIT_PERCEPTION', stage:'perception_received', status:'no_target / low_confidence', action:'re_perception', next:'WAIT_PERCEPTION', risk:'low', sceneRisk:'low', note:'重新识别，不改变场景。' },
    { source:'VALIDATE_TARGETS', stage:'targets_validated', status:'pose_abnormal / transform_failed', action:'reposition_chassis', next:'MOVE_TO_WORKPOSE', risk:'medium', sceneRisk:'medium', note:'识别姿态不可信，优先重新到位。' },
    { source:'PLAN_PREGRASP', stage:'pre_grasp_planned', status:'planning_failed', action:'retry_same_target / mark_target_failed', next:'PLAN_PREGRASP / SELECT_TARGETS', risk:'medium', sceneRisk:'low', note:'目标存在但规划不到。' },
    { source:'CHECK_VACUUM', stage:'vacuum_confirmed', status:'vacuum_abnormal', action:'retry_same_target / re_perception', next:'APPROACH_CONTACT / WAIT_PERCEPTION', risk:'medium', sceneRisk:'medium', note:'可能没吸住，不能继续 attach。' },
    { source:'EXTRACT_BOX', stage:'extract_executed', status:'partial_pullout / dropped_after_pullout', action:'re_perception / manual_intervention', next:'WAIT_PERCEPTION / WAIT_MANUAL_RECOVERY', risk:'high', sceneRisk:'high', note:'真实箱子状态已变化，旧场景不可信。' },
    { source:'CARRY_BOX', stage:'transfer_executed', status:'force_abnormal / vacuum_abnormal', action:'emergency_stop / re_perception', next:'E_STOP / WAIT_PERCEPTION', risk:'high', sceneRisk:'high', note:'带箱搬运中风险最高。' },
    { source:'UPDATE_PLACED_SCENE', stage:'scene_placed_updated', status:'scene_update_failed', action:'manual_intervention / re_perception', next:'WAIT_MANUAL_RECOVERY / WAIT_PERCEPTION', risk:'high', sceneRisk:'high', note:'MoveIt 世界不可信，不能进入下一轮正常抓取。' }
  ]
}
